---
# environment file for hadenlabs.ansible-role-template

- name: Create files role_name
  become: true
  file:
    path: '{{ item.path }}'
    state: '{{ item.state }}'
    owner: '{{ item.owner }}'
  with_items: '{{ _role_name_create_files | default({}) }}'
  when: _role_name_create_files is defined
